# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-19 09:10
from __future__ import unicode_literals

import deploy.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0003_auto_20190215_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['modules'],
            },
        ),
        migrations.CreateModel(
            name='FileRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default=None, max_length=244, verbose_name='\u8fdc\u7a0b\u4e3b\u673a')),
                ('cur_path', models.CharField(max_length=244)),
                ('bak_path', models.CharField(max_length=244)),
                ('file_tag', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('is_group', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u5907\u4efd',
                'verbose_name_plural': '\u6587\u4ef6\u5907\u4efd\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u4e3b\u673a')),
                ('file_name', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file_path', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u4e0a\u4f20')),
                ('remote_path', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u8def\u5f84')),
                ('file_tag', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20\u7ba1\u7406',
                'permissions': (('view_filemanage', '\u67e5\u770b\u6587\u4ef6\u7ba1\u7406'), ('edit_fileupload', '\u7ba1\u7406\u6587\u4ef6\u4e0a\u4f20'), ('edit_filedownload', '\u7ba1\u7406\u6587\u4ef6\u4e0b\u8f7d')),
            },
        ),
        migrations.CreateModel(
            name='FileUploadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=244, verbose_name='\u4e3b\u673a\u7ec4\u540d\u79f0')),
                ('file_name', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file_path', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u4e0a\u4f20')),
                ('remote_path', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u8def\u5f84')),
                ('file_tag', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20\u7ba1\u7406',
                'permissions': (('view_filemanage', '\u67e5\u770b\u6587\u4ef6\u7ba1\u7406'), ('edit_fileupload', '\u7ba1\u7406\u6587\u4ef6\u4e0a\u4f20'), ('edit_filedownload', '\u7ba1\u7406\u6587\u4ef6\u4e0b\u8f7d')),
            },
        ),
        migrations.CreateModel(
            name='jids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255, unique=True)),
                ('load', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Models_fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(max_length=50)),
                ('func', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['modules'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAttchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attchment', models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/HjDHkGL5JERjknVqfYYq7YSaYXPqsXeWHRhCj3efYgcHMBQkVF7b84rTgXwSyRgjjjSSdLWlcyq8R5sm', verbose_name='\u6a21\u5757\u4e0a\u4f20')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('module', models.CharField(max_length=50, verbose_name='\u8c03\u7528\u6a21\u5757')),
                ('module_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6a21\u5757\u8def\u5f84')),
                ('visible', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u53ef\u89c1\u7b49\u7ea7')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('attchment', models.ManyToManyField(related_name='module_attchment', to='deploy.ModuleAttchment', verbose_name='\u6a21\u5757\u4e0a\u4f20')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ManyToManyField(blank=True, related_name='module_usergroup_set', to='userauth.UserGroup', verbose_name='\u6240\u5c5e\u7528\u6237\u7ec4')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u6a21\u5757',
                'verbose_name_plural': 'Salt\u6a21\u5757\u7ba1\u7406',
                'permissions': (('edit_module', '\u7ba1\u7406Salt\u6a21\u5757'),),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u9879\u76ee')),
                ('src', models.CharField(max_length=255, verbose_name='rsync\u6a21\u5757\u540d\u79f0')),
                ('src_user', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='\u6e90\u7528\u6237')),
                ('src_passwd', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='\u6e90\u7528\u6237\u5bc6\u7801')),
                ('path', models.CharField(max_length=255, verbose_name='\u9879\u76ee\u8def\u5f84')),
                ('process', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='\u9879\u76ee\u8fdb\u7a0b')),
                ('salt_test', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='\u6d4b\u8bd5\u73af\u5883')),
                ('salt_group', models.CharField(max_length=255, verbose_name='\u6b63\u5f0f\u73af\u5883')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_usergroup_set', to='userauth.UserGroup', verbose_name='\u7528\u6237\u7ec4')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': '\u9879\u76ee\u7ba1\u7406',
                'default_permissions': (),
                'verbose_name': '\u9879\u76ee',
                'permissions': (('view_project', '\u67e5\u770b\u9879\u76ee'), ('edit_project', '\u7ba1\u7406\u9879\u76ee')),
            },
        ),
        migrations.CreateModel(
            name='salt_event_returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(db_index=True, max_length=50)),
                ('jid', models.CharField(db_index=True, max_length=255)),
                ('fanhui', models.TextField()),
                ('node', models.CharField(db_index=True, max_length=255)),
                ('fun_args', models.CharField(blank=True, max_length=255)),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField()),
                ('alter_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-alter_time'],
            },
        ),
        migrations.CreateModel(
            name='SaltGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True, verbose_name='Salt\u5206\u7ec4')),
                ('groupname', models.CharField(max_length=80, unique=True)),
                ('department', models.ManyToManyField(blank=True, related_name='saltgroup_department_set', to='userauth.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u5206\u7ec4',
                'verbose_name_plural': 'Salt\u5206\u7ec4\u7ba1\u7406',
                'permissions': (('edit_saltgroup', '\u7ba1\u7406Salt\u4e3b\u673a\u5206\u7ec4'),),
            },
        ),
        migrations.CreateModel(
            name='SaltHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=80, unique=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('alive', models.BooleanField(default=False, verbose_name='\u8fde\u901a\u72b6\u6001')),
                ('alive_time_last', models.DateTimeField()),
                ('alive_time_now', models.DateTimeField()),
                ('status', models.BooleanField(default=False, verbose_name='\u662f\u5426\u52a0\u5165salt\u7ba1\u7406')),
                ('department', models.ManyToManyField(related_name='host_department_set', to='userauth.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('user_group', models.ManyToManyField(related_name='host_usergroup_set', to='userauth.UserGroup', verbose_name='\u6240\u5c5e\u7528\u6237\u7ec4')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u4e3b\u673a\u6388\u6743',
                'verbose_name_plural': 'Salt\u4e3b\u673a\u6388\u6743\u7ba1\u7406',
                'permissions': (('view_deploy', '\u67e5\u770b\u4e3b\u673a\u90e8\u7f72'), ('edit_deploy', '\u7ba1\u7406\u4e3b\u673a\u90e8\u7f72')),
            },
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='minions',
            field=models.ManyToManyField(related_name='salt_host_set', to='deploy.SaltHost', verbose_name='Salt\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='user_group',
            field=models.ManyToManyField(related_name='group_usergroup_set', to='userauth.UserGroup', verbose_name='\u6240\u5c5e\u7528\u6237\u7ec4'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.SaltHost'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
