# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 02:29
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/QsVSWsB4C6pmkWmFaufSRnHS7pTEhpEbPp6rnlSrXLwU3HaKSlAwxkxMn5tmUsH8aJxt5ps9atRCCtqx', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
