# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-19 09:11
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/6BnCqrvudR5es3AnJ54nfNETM7jc7YWRCsSYBBkMVJatSHp9TJCgGVfPn8tvsRN9UFGkyY8t7fBApVVk', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
