# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 06:45
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20181212_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='jids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255)),
                ('load', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/QR9xPheBmUek8DTghK5EB8laXsjKxTHHCTsNek9vLJyRPh6WGe9fAFYGb637ldBBmFfXs5jvUqkfHfql', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterIndexTogether(
            name='jids',
            index_together=set([('jid',)]),
        ),
    ]
