# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 01:47
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20190201_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/jQt4h3NRUc9a3fHBc5VFx9HX9xtSG8FfjwDnkeKLXtVPq7SLgXJd4JhFrAvFq5yfQtDUbJr9UPPAVLem', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
