# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:03
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20181218_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='salt_returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(max_length=50)),
                ('jid', models.CharField(max_length=255)),
                ('fanhui', models.TextField()),
                ('node', models.CharField(max_length=255)),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField()),
                ('alter_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/nSaCKRMAWm4gqb7M4e9E55xGBaTVBH5LKGVuWkEXCs9grHd3x5Whw5jWuaf8UtsbRdnESqkbN8CvNNbJ', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterIndexTogether(
            name='salt_returns',
            index_together=set([('fun',)]),
        ),
    ]
