# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:05
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20181218_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salt_returns',
            new_name='salt_event_returns',
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/T8a8KYKdnQhmtQMtFsGyUQNVkjA7KXtWXCjLmnU4DeWEUpKuVrv4BaK4hyH7YMv5l5pKBHtX5Na3QPUB', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
