# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-19 09:19
from __future__ import unicode_literals

import deploy.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0005_auto_20191119_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='\u6807\u7b7e')),
                ('env', models.CharField(max_length=1, verbose_name='\u53d1\u5e03\u73af\u5883')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/CxD4KvqGs8wH8rfMYpT6WbyxTLWv8E7M5CjTpPPDMDSM6pKj46NkfeAAPdrmgjFKhg8AKqpYdhJHDDSR', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
