# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 06:42
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20190201_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salthost',
            options={'default_permissions': (), 'permissions': (('view_deploy', '\u67e5\u770b\u4e3b\u673a\u90e8\u7f72'), ('edit_deploy', '\u7ba1\u7406\u4e3b\u673a\u90e8\u7f72')), 'verbose_name': 'Salt\u4e3b\u673a\u6388\u6743', 'verbose_name_plural': 'Salt\u4e3b\u673a\u6388\u6743\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/RcSLFfEL4FCFDVkaMGHsXJMtAWB3ULQdt5PxVwH54tBF9tUw4JP3eQByArpmTLhMTNx6Pr9HC3spHkEU', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
