# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:15
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20181218_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jids',
            name='jid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/aCq9VGf7WrLHAUxe69EKAgebaUtChjja7GBd9nNx4kTv3rldCpcBGDPnLKvVHcLm3wmr3KEkGlMbVEp3', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterIndexTogether(
            name='jids',
            index_together=set([]),
        ),
    ]
