# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-27 09:28
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20191119_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salthost',
            options={'default_permissions': (), 'permissions': (('view_deploy', '\u67e5\u770b\u4e3b\u673a\u90e8\u7f72'), ('edit_deploy', '\u7ba1\u7406\u4e3b\u673a\u90e8\u7f72')), 'verbose_name': 'Salt\u4e3b\u673a\u6388\u6743', 'verbose_name_plural': 'Salt\u4e3b\u673a\u7ba1\u7406'},
        ),
        migrations.AlterModelManagers(
            name='fileupload',
            managers=[
                ('dahl_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/dTQsGY6B9BxT4YRkuBedVvsdkqBpjbPCxWv3mdPjpxlMex7HnYsu9D9RQwvjqHxWcNmpE9gDGy5a7Ghk', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salthost',
            name='alive_time_last',
            field=models.DateTimeField(verbose_name='\u4e0a\u6b21\u4e0a\u7ebf\u65f6\u95f4\u4e3a'),
        ),
    ]
