# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 06:47
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20190215_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/8HXXRb6uwGKbr8yGN96lXbBChN3rYS9pKJelVWMrsrQENdvTnRLy6Yqyn7yPJ6gmHVyASgLhspVNFr9s', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
