# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 06:50
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20190215_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/g6yUgSP46nNJ4jWmKyrQ7VdAhkxvHXMulBG5nFKxbeGsUVDGHeBhxG7CYgcPanqUfmTcL9f4sKcH5N7m', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
