# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-27 09:37
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20191227_1735'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fileupload',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/SfqyF3EnrucdeUCH9m3mL6jSKmWQhskjKQaw39yNH6hPJl8jSSGx369PGBHl8Mu6d5ns5YjgJQDu6SGU', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
