# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-27 09:44
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20191227_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/MXjvpCmkENCjJAaeXYMq4txBN9rTsRgu9ucFydJYjtT9vgnd3VFU8SJADaWetBxFpQLaGbw8tuYGNDWR', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
