# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-12 02:00
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20190215_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/yqkqyMPh5YBNDmglrbTNxEX75PVrvnaRuuBV7bwSjtwaPBVvjfJDKPhUKvNxvXENsyW4KP6NU3F5F5EK', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salthost',
            name='alive_time_last',
            field=models.DateTimeField(),
        ),
    ]
