# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:17
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20181218_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/63dEN4VqDeGVjFHN9krYQHwTsBtl7t7unme5pNmftySWkUxSW9U4xYVQxNtlTswK7kjKcfj4tMgR3R7j', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
