# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-27 09:47
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20191227_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/RS7YyQHT8L5tKFkUCQBxEEk9fXjfGxXTpbKtaaLjXFteXHw7awffCUBea8RydHHNNwxR6Ln5LhGU9qc5', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
