# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-12 02:03
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auto_20190912_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/VykNSQjTVCTlxEBmJJb5lbmGGm4cbUk8J4qHtcPAU8GLQvlCLbt6yWKB6a7N8F67e88EBN6XRyyH3sbm', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salthost',
            name='alive_time_now',
            field=models.DateTimeField(),
        ),
    ]
