# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-28 07:11
from __future__ import unicode_literals

import deploy.models
import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20190912_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='target',
            field=models.FileField(upload_to=b'', verbose_name=deploy.models.SaltHost),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/drtSuQB4RG9DVWDyJCSJNsedfxbqntLyRDlb4Ym7wCFwmMpbGNykwsvtTTLkYw6jntwTxac3FSeYTBDQ', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
