# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:23
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_auto_20181218_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jids',
            name='jid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/qmQP6GXnvMPGEaATSBRKVvL7PUnAlVV5xqEq9GfGhGAV7gQ9HHTbDMt7eMkcl3m4HLQMl8asAuCDHyrf', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
