# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-28 08:25
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20191028_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='target',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/AhvwcQa4aJpHT5uWS5BRHP5BSar79lqmyFLWVjclPtmY7laqrNqBdNrHWhQ63yrqF8dhE7udh7knbAk7', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
