# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-28 09:34
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_auto_20191028_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_tag',
            field=models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/E3RFCjbUBWynhND7B6xJfTBQtbpAkdegGcn3HmL9HeEtQw6LST5CtUM4PKJaYf6MMycjyde4pahuwxJA', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
