# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:29
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_auto_20181218_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jids',
            name='jid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/P9UtpDn8A5tHcEcgjd6hAaumhNxnKBYqNSuVWqgVak6qhqbNFYvPJgfkmNQPAGpghDDuwtuxGLR8CBly', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
