# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-28 09:38
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20191028_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='target',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='target_name',
            new_name='host_name',
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/FjJFCPRg938LPFtCce4qgmx3c69fpsyH3Brp4Kv4Qy6emGpKLDaVapHVrH89uGLHkjQ8cGp8VPVdRCMl', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
