# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-30 08:24
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20191028_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_path',
            field=models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/b7J9VjrFxQvMuv5nAs5RGChTEBqAxBbjHCkcCG9JN9LG4xjjxK4Ye8XhrXn7SMwjpK4unMveEHNubsxJ', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
