# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:33
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20181218_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/CJRuFKBHcWJTEdqmSVcprBJNJdeGWK6ClKFNptTpgK5le5faYNwtQUQw8wLAv4SkfkM4Fd8VtYNpvxpS', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='fun',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='jid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='node',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
