# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-04 03:05
from __future__ import unicode_literals

import deploy.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0021_auto_20191030_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u4e3b\u673a')),
                ('file_name', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file_path', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u4e0a\u4f20')),
                ('remote_path', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u8def\u5f84')),
                ('file_tag', models.CharField(max_length=244, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20\u7ba1\u7406',
                'permissions': (('view_filemanage', '\u67e5\u770b\u6587\u4ef6\u7ba1\u7406'), ('edit_fileupload', '\u7ba1\u7406\u6587\u4ef6\u4e0a\u4f20'), ('edit_filedownload', '\u7ba1\u7406\u6587\u4ef6\u4e0b\u8f7d')),
            },
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/NWp9tWQXkeWXmnVHVnlJUleMPqkY57xmldDfHxSUBgT78pYrP5ClRBgSE3hP6yCJG5nUeSMCxAPLu5wq', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
