# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-04 03:06
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0022_auto_20191104_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadgroup',
            name='group_name',
            field=models.CharField(max_length=244, verbose_name='\u4e3b\u673a\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/LRprB44rsrwcEmsmuVTYF7eGPvlpklvaeUf6K7n86Cbeac8SKkRy83dLQB7t9x7YhLRcyAgyX553cXRB', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
