# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:46
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0024_auto_20181218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/MDnTvGmXFBQc7XtLyUVWXFk4Thhf7jtQv7cClFDkxsKvAE5MFwsgCeAHqbnVNM983shM5ueew8yMAUsx', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='alter_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
