# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:48
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0025_auto_20181218_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/7863uayjdS8pNlfVHk4gltgt5hdkc5QCbKfMQtat7WxDjV89DMrX5cxCAM64hHyMek7vt8MerNrXySRy', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='alter_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
