# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:55
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0027_auto_20181218_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/vlR6PCUaBKxKKrLMynwPSxMbBypcT9pmEm8CCgGQVNgGRTatShmweJdeBcwmq5SM5MLJLlV4C3uSvQsj', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='alter_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
    ]
