# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:59
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0029_auto_20181218_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salt_event_returns',
            name='alter_time',
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/5htFFk4TVsv4m9nuGRqly3JMKtgvG77VMH9PYxbQBgvapv7wE4wSQQacg7WqBJLp4QFAVQrWdSSPbGVj', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
