# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 04:11
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0031_auto_20181218_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salt_event_returns',
            options={'ordering': ['-alter_time']},
        ),
        migrations.AddField(
            model_name='salt_event_returns',
            name='fun_args',
            field=models.CharField(db_index=True, default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/yvD4q4nVJ5Luhesv9dfpYD3QyMFCxHWDUyGEn6G34skU9wVTKg5H7jgRB6QjVkVABTYj5qdFUsBKj9Xt', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
