# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 04:40
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0034_auto_20181219_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/4kacDSsUByPbH39VjwrMdN38fsexgYqxkqQh9A5d7XXQXKSadkYCQvJhwrcg5cU3WN9kCfHugQrqyeng', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='salt_event_returns',
            name='fun_args',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
