# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 04:46
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0036_auto_20181219_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salt_event_returns',
            name='fun_args1',
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/W6eMGUsMVvcJh5T3YwJTytW8tm5rVAjQTAARnvHQJ6W9RkrayRMcQfvPXmKUWpCVScSuarwug5B6Qs53', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
