# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 09:25
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0038_auto_20181219_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_fun',
            name='func',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='models_fun',
            name='modules',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/aFTElNdd8HBAbtMRDuE7QMWl4PpBKdd7EU4LjBC5hxQa3ESk8byCcXJwKCjUKPq5t9wUKLvj4KjP5cVp', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
