# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 09:26
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0039_auto_20181219_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_fun',
            name='modules',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/YbcAybn9DhmRsPsktxuFMJ6TQhr5a7B79NUAGFVnn7eGhlqxCerXtpqjXt6ER46u6yPFgGRwmCtAjdLx', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
