# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 10:01
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0040_auto_20181219_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_fun',
            name='func',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='models_fun',
            name='modules',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/ysUXG8bUMhXXm3SffBMtpfENnDLEPHwvuVgbVHW5fw3f4mg6BMJrxQu8GDFkGCXHBe7KJnF9wM9uJEXt', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
