# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 10:02
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0041_auto_20181219_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/ClHcek98wpuLLsbHHvrvUNx4TwsNRK5AuYJ6knkPYXhks7ShK44PueljG5xarLET4l63Yu9PXSermYN8', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
