# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-25 03:19
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0042_auto_20181219_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models_fun',
            options={'ordering': ['modules']},
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/FyKXgqxnlDuVsStSJRlgDucU37WLdNMnqlRkULJbBmHDXXeQVwwRt9YutVAEHNA5yBbABQsF9gRttRve', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
