# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 09:11
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0043_auto_20181225_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['modules'],
            },
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/9YWeJnvdaYhVkHsGdnKHRNKBD8BnHcG7wUSu4AFa5QCvUR73aclKyctyftT8yhUGDYs4wnLuTGQfEYs4', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
