# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 10:04
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0044_auto_20190109_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt_event_returns',
            name='fun_args',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/VGBmbYLcdVgPRqmGjeDP7tm4dVlnYQHus5exQf6UDN6c8RPbh3b45KhNF4mVYaST78lrhHKc6kqqHsVQ', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
