# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-25 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userperm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='host',
            field=models.CharField(default='localhost', max_length=50, verbose_name='\u8282\u70b9'),
        ),
    ]
