# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverasset',
            name='sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5e8f\u5217\u53f7'),
        ),
    ]
