# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20190215_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('view_user', '\u67e5\u770b\u7528\u6237'), ('edit_user', '\u7ba1\u7406\u7528\u6237')), 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237\u7ba1\u7406'},
        ),
    ]
